<?php

/**
 * Implements hook_help().
 */
function custom_pub_help($path, $arg) {
  switch ($path) {
    case 'admin/help#custom_pub':
      return '<p>'. t("Custom Publishing Options allows you to create custom publishing options for nodes. It allows you to add to the default options of Publish, Promote to Front Page, and Sticky. It also ingrates with views to allow you add as a field, sort and filter by, your custom options.") .'</p>';
    case 'admin/content/custom_pub':
      return '<p>'. t("Custom Publishing Options allows you to create custom publishing options for nodes. It allows you to add to the default options of Publish, Promote to Front Page, and Sticky. It also ingrates with views to allow you add as a field, sort and filter by, your custom options.") .'</p>';
  }
}

/**
 * Implements hook_permissions()
 * 
 * We use these permissions on the inidvidual elements in the
 * node_form via the #access parameter. So in order to use the elements
 * you must add the permissions to a role.
 */
function custom_pub_permissions() {
  $types = variable_get('custom_pub_types', array());
  foreach ($types as $type) {
    $key = 'edit_custom_pub_' . $type['type'];
    $perms[$key] = array(
      'title' => 'Toggle ' . $type['type'] . ' custom options'
    );
  }
  return $perms;
}

/**
 * Implements hook_theme()
 */
function custom_pub_theme() {
  return array(
    'custom_pub_edit_form' => array(
      'file' => 'theme.inc',
      'path' => drupal_get_path('module', 'custom_pub'),
      'render element' => 'form',
    ),
  );
}

/**
 * Implements hook_menu()
 */
function custom_pub_menu() {
  $items['admin/structure/custom_pub'] = array(
    'title' => 'Publishing Options',
    'page callback' => 'custom_pub_admin',
    'access arguments' => array('administer nodes'),
    'description' => 'Add and remove custom publishing options from the Node form.',
    'file' => 'custom_pub.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_menu_alter().
 */
function custom_pub_menu_alter(&$items) {
  $items['admin/content']['module'] = 'custom_pub';
  $items['admin/content']['file'] = 'custom_pub.admin.inc';
}

/**
 * Implements hook_forms()
 */
function custom_pub_forms($form_id, $args) {
  //We need to use this hook because on the admin page there is the possiblity of multiple forms for the edit form. See http://drupal.org/node/354519
  $types = variable_get('custom_pub_types', array());
  foreach ($types as $type) {
    if ($form_id == 'custom_pub_edit_'.$type['type']) {
      $forms[$form_id] = array('callback' => 'custom_pub_edit');
      return $forms;
    }
  }
  if ($form_id == 'node_admin_content') {
    module_load_include('inc','node', 'node.admin');
    $forms['node_admin_content'] = array(
      'callback' => 'custom_pub_node_admin_content',
    );
    return $forms;
  }
}

/**
 * Implements hook_form_alter()
 */
function custom_pub_form_alter(&$form, $form_state, $form_id) {
  //add the options to the node form
  $access = FALSE;
  if (isset($form['#node_edit_form']) && $form['#node_edit_form'] === TRUE) {
    $node = $form['#node'];
    $types = custom_pub_by_node_type($node);
    foreach ($types as $type) {
      $form['options'][$type['type']] = array(
       '#type' => 'checkbox',
       '#title' => t($type['name']),
       '#default_value' => $node->{$type['type']},
       '#access' => user_access('administer nodes') ? TRUE : user_access('edit_custom_pub_' . $type['type']),
      );
      //If $access is already set to true we don't want to override it. Once it's TRUE then it should stay TRUE
      //If it's not TRUE though then we should set it to the current access value
      $access = empty($access) ? user_access('edit_custom_pub_' . $type['type']) : TRUE;
    }
    //If after we loop through the types there is at least one that is being set by a custom permission
    //Then we need to alter the default asscess on the options tab and it's default options
    if ($access) {
      $form['options']['#access'] = $access;
      $form['options']['status']['#access'] = 
      $form['options']['promote']['#access'] =
      $form['options']['sticky']['#access'] = user_access('administer nodes');
    }
  }
  //Add options to the node_type_form for editing default node options
  if ($form_id == 'node_type_form'){
    $node_type = $form['#node_type'];
    $types = custom_pub_by_node_type($node_type);
    foreach ($types as $type) {
      $form['workflow']['node_options']['#options'][$type['type']] = t($type['name']);
    }
  }
  if ($form_id == 'node_admin_content') {
    if (isset($form_state['values']['operation']) && $form_state['values']['operation'] == 'delete') {
      //Kind of dumb that we have to do this here but because of the way we call our form and include the node.admin file
      //We have no choice because on delete operations we end up losing control of the the form
      //But we then get it back when the confirm button is pressed leaving us with out the required file loaded
      //Thats why we add a submit handler to the start that then loads the file needed and then the node submit handler can work
      array_unshift($form['#submit'], 'custom_pub_node_admin_inc_add');
    }
  }
}

/**
 * Implements hook_views_data_alter()
 */
function custom_pub_views_data_alter(&$data){
  $types = variable_get('custom_pub_types', array());
  $node_types = _node_types_build();
  foreach ($types as $type) {
    $used_in = array();
    foreach ($node_types->types as $node_type) {
      if (!empty($type['node_types'][$node_type->type])) {
        $used_in[] = $node_type->name;
      }
    }
    // published status
    $data['node'][$type['type']] = array(
    'title' => t($type['name']),
    'help' => t('Custom Publishing Option. Appears in: !types', array('!types' => implode(', ', $used_in))),
    'field' => array(
      'handler' => 'views_handler_field_boolean',
      'click sortable' => TRUE,
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_boolean_operator',
      'label' => t($type['name']),
      'type' => 'yes-no',
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    );
  }
}

/**
 * Implements hook_schema_alter()
 */
function custom_pub_schema_alter(&$schema) {
  $types = variable_get('custom_pub_types', array());
  foreach ($types as $type) {
    $schema['node']['fields'][$type['type']] = array(
      'description' => t('Custom publishing option @name',array('@name' => $type['name'])),
      'type' => 'int',
      'not null' => TRUE,
      'default' => 0,
    );
  }
}

/**
 * Implements hook_action_info().
 */
function custom_pub_action_info() {
  $actions["custom_pub_on_action"] = array(
    'type' => 'node',
    'description' => t('Toggle a Custom Publishing Option on'),
    'configurable' => TRUE,
    'behavior' => array('changes_node_property'),
    'hooks' => array(
      'nodeapi' => array('presave'),
      'comment' => array('insert', 'update'),
    ),
  );
  $actions["custom_pub_off_action"] = array(
    'type' => 'node',
    'description' => t('Toggle a Custom Publishing Option off'),
    'configurable' => TRUE,
    'behavior' => array('changes_node_property'),
    'hooks' => array(
      'nodeapi' => array('presave'),
      'comment' => array('delete', 'insert', 'update'),
    ),
  );

  return $actions;   
}

/**
 * Implements a configurable action
 * Toggles a custom publishing option on as an action
 * 
 * @param $node
 *   The node object of the current node
 * 
 * @param $context
 *   The avaialable context of the current action
 */
function custom_pub_on_action(&$node, &$context) {
  //This is mainly for the Rules Module. I couldn't get a node to save unless I set this manually
  $context['auto_save'] = TRUE;
  $types = variable_get('custom_pub_types', array());
  foreach ($context['types'] as $type) {
    if (!empty($type) && in_array($node->type, array_keys($types[$type]['node_types']))) {
      $node->$type = 1;
      watchdog('action', 'Toggled @type %title custom publishing option: @label to on.', array('@type' => node_get_types('name', $node), '%title' => $node->title, '@label' => $types[$type]['name']));
    }
  }
}

/**
 * Implements a configurable action form
 * Allows the user to pick custom publishing options to turn on.
 */
function custom_pub_on_action_form($context) {
  $types = variable_get('custom_pub_types', array());//get the current custom publishing types
  foreach ($types as $type) {
    $pub_types[$type['type']] = $type['name'];
  }
  $form['types'] = array(
    '#title' => t('Custom Publishing Options'),
    '#description' => t('Select the Custom publishing options to toggle on when this action is triggered.'),
    '#type' => 'checkboxes',
    '#options' => $pub_types,
    '#default_value' => isset($context['types']) ? $context['types'] : array(),
  );
  
  return $form;
}

function custom_pub_on_action_submit($form, &$form_state) {
  return array('types' => $form_state['values']['types']);
}

/**
 * Implements a configurable action
 * Toggles a custom publishing option off as an action
 * 
 * @param $node
 *   The node object of the current node
 * 
 * @param $context
 *   The avaialable context of the current action
 */
function custom_pub_off_action(&$node, &$context) {
  //This is mainly for the Rules Module. I couldn't get a node to save unless I set this manually
  $context['auto_save'] = TRUE;
  $types = variable_get('custom_pub_types', array());
  foreach ($context['types'] as $type) {
    if (in_array($node->type, array_keys($types[$type]['node_types']))) {
      $node->$type = 0;
      watchdog('action', 'Toggled @type %title custom publishing option: @label to off.', array('@type' => node_get_types('name', $node), '%title' => $node->title, '@label' => $types[$type]['name']));
    }
  }
  return array('node' => $node);
}

/**
 * Implements a configurable action form
 * Allows the user to pick custom publishing options to turn off.
 */
function custom_pub_off_action_form($context) {
  $types = variable_get('custom_pub_types', array());//get the current custom publishing types
  foreach ($types as $type) {
    $pub_types[$type['type']] = $type['name'];
  }
  $form['types'] = array(
    '#title' => t('Custom Publishing Options'),
    '#description' => t('Select the Custom publishing options to toggle off when this action is triggered.'),
    '#type' => 'checkboxes',
    '#options' => $pub_types,
    '#default_value' => isset($context['types']) ? $context['types'] : array(),
  );
  
  return $form;
}

function custom_pub_off_action_submit($form, &$form_state) {
  return array('types' => $form_state['values']['types']);
}

/**
 * Implements hook_query_TAG_alter()
 */
function custom_pub_query_node_load_multiple_alter($query) {
  $types = variable_get('custom_pub_types', array());
  if (count($types)) {
    foreach ($types as $field => $types) {
      $query->addField('base', $field);
    }
  }
}

/**
 * Implements hook_node_prepare().
 */
function custom_pub_node_prepare($node) {
  $types = custom_pub_by_node_type($node);
  // If this is a new node, fill in the default values.
  if (!isset($node->nid)) {
    $node_options = variable_get('node_options_'. $node->type, array('status', 'promote'));
    foreach (array_keys($types) as $key) {
      if(!isset($node->$key)) {
        $node->$key = in_array($key, $node_options);
      }
    }
  }
}

/**
 * Returns only the custom types available for the given node type
 * 
 * @param $type
 *   Can be either a string of the node type or an object/array with a key of 'type'
 * 
 * @return
 *   An array of the custom pub types that are avaialbe for that node->type
 */
function custom_pub_by_node_type($n_type) {
  $return_types = array();
  if (is_object($n_type) || is_array($n_type)) {
    (object)$n_type;
    $n_type = $n_type->type;
  }
  $types = variable_get('custom_pub_types', array());
  foreach ($types as $key => $type) {
    if (!empty($type['node_types'][$n_type])) {
      $return_types[$key] = $type;
    }
  }
  return $return_types;
}
